# Stage 1: Build
FROM maven:3.8.6-eclipse-temurin-17 AS build
WORKDIR /opt/app

# Копируем весь проект, чтобы Maven видел parent POM
COPY . .

# Собираем только модуль auth-service и его зависимости (parent POM)
RUN mvn clean install -DskipTests -pl discovery-server -am

# Stage 2: Runtime
FROM eclipse-temurin:17-jre-jammy
WORKDIR /opt/app

# Пробрасываем порт сервиса
EXPOSE 8761

# Копируем готовый jar из stage build
COPY --from=build /opt/app/discovery-server/target/*.jar /opt/app/app.jar

# Команда запуска
ENTRYPOINT ["java", "-jar", "app.jar"]
